name: discord-ai

volumes:
  db-data:
  venv-data:
  pgadmin-data:

services:
  bot:
    build: .
    image: ghcr.io/kvdomingo/discord-ai
    restart: unless-stopped
    init: true
    volumes:
      - ./:/app
      - venv-data:/app/.venv
    depends_on:
      db:
        condition: service_healthy

  db:
    image: ghcr.io/kvdomingo/postgresql-pig-standalone:17-bitnami
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/bitnami/postgresql
      - ./db-init:/docker-entrypoint-initdb.d:ro
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}", "-d", "${POSTGRESQL_DATABASE}" ]
      timeout: 2s
      start_interval: 5s
      interval: 20s
      start_period: 60s

  rest:
    image: postgrest/postgrest:v12.2.8
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgres://${POSTGRESQL_USERNAME}:${POSTGRESQL_PASSWORD}@db:5432/${POSTGRESQL_DATABASE}
      PGRST_DB_SCHEMAS: public
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_JWT_IS_BASE64: ${PGRST_JWT_IS_BASE64}
      PGRST_DB_ANON_ROLE: anon
    ports:
      - '3000:3000'
    depends_on:
      db:
        condition: service_healthy

  swagger:
    image: swaggerapi/swagger-ui:v5.18.3
    restart: unless-stopped
    environment:
      API_URL: http://localhost:3000
    ports:
      - '8080:8080'
    depends_on:
      - rest

  pgadmin:
    image: dpage/pgadmin4:9
    restart: unless-stopped
    environment:
      PGADMIN_LISTEN_HOST: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5000
      PGADMIN_DEFAULT_EMAIL: hello@kvd.studio
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/pgadmin
    ports:
      - '5000:5000'
