name: discai

volumes:
  db-data:
  venv-data:

services:
  bot:
    build: .
    image: ghcr.io/kvdomingo/discai:dev
    restart: unless-stopped
    environment:
      GOOGLE_GENAI_USE_VERTEXAI: false
      PYTHON_ENV: development
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
      GOOGLE_CLOUD_LOCATION: ${GOOGLE_CLOUD_LOCATION}
      OPENWEATHERMAP_API_KEY: ${OPENWEATHERMAP_API_KEY}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      CHAT_MODEL: ${CHAT_MODEL}
      TITLE_MODEL: ${TITLE_MODEL}
      JEV_TOKEN: ${JEV_TOKEN}
      SERPER_API_KEY: ${SERPER_API_KEY}
    volumes:
      - .:/app
      - venv-data:/app/.venv
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: pyproject.toml
          action: restart
        - path: uv.lock
          action: restart

  db:
    image: ghcr.io/kvdomingo/postgresql-pig:18
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    volumes:
      - db-data:/var/lib/postgresql
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRESQL_USERNAME}",
          "-d",
          "${POSTGRESQL_DATABASE}",
        ]
      timeout: 2s
      interval: 20s
      start_period: 10s
      retries: 3
