[project]
name = "discord-ai"
version = "0.2.0"
description = ""
readme = "README.md"
requires-python = "~=3.14.0"
dependencies = [
    "asyncpg~=0.30",
    "dependency-injector>=4.49.1",
    "discord-py~=2.0",
    "httpx>=0.28.1",
    "langchain>=1.4.3",
    "langchain-google-genai>=4.3.7",
    "loguru~=0.7",
    "psycopg2-binary~=2.0",
    "pydantic~=2.0",
    "pydantic-settings~=2.0",
    "requests~=2.0",
    "sqlalchemy[asyncio]~=2.0",
    "typesafe-sdk[http2]>=0.7.2",
]

[dependency-groups]
dev = [
    "ipython~=9.0",
    "pytest~=9.1",
    "ruff~=0.9",
    "ty>=0.0.27",
    "watchdog[watchmedo]~=6.0",
]
