name: "[Pipeline] Deploy"
on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  deploy-api:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: git.lab.kvd.studio
          username: ${{ gitea.repository_owner }}
          password: ${{ secrets.GCR_PASSWORD }}

      - name: Extract container metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: git.lab.kvd.studio/${{ gitea.repository_owner }}/discai
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push container
        uses: docker/build-push-action@v5
        with:
          file: prod.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
